### ISSUE TITLE
Add authentication to the data/ endpoints using application tokens 

### ISSUE THREAD

**Issue by MichaelWashburnJr** [BrewCenter/BrewCenterAPI#28]
There are API endpoints in the brew_data module that have not been updated to accept the new TokenAuthentication mechanism defined in brewcenter_api/accounts/auth. To do this you'll have to import accounts and add accounts.auth.TokenAuthentication to the authentication classes for each class based view.

**Comment by StrawHatDragon100** [comment]
can i work on this ?

**Comment by MichaelWashburnJr** [comment]
@StrawHatDragon100 Sure thing!
