### ISSUE TITLE
Setup main documentation page

### ISSUE THREAD

**Issue by MichaelWashburnJr** [BrewCenter/BrewCenterAPI#29]
May just want to use django rest frameworks builtin docs but with enhanced views. Either way, this needs an index of all the endpoints, and an overview of the data structure, without giving away all the data.

**Comment by emman27** [comment]
I believe this immediately solves your problem...
https://github.com/marcgibbons/django-rest-swagger

**Comment by MichaelWashburnJr** [comment]
hey hey hey, this looks nice. Feel free @emman27

**Comment by emman27** [comment]
@MichaelWashburnJr Hmm this is significantly more difficult than I expected - any particular reason you've chosen to use APIViews over Viewsets, and urlpatters over DefaultRouter? If not, I actually think that would make a far more useful improvement

**Comment by MichaelWashburnJr** [comment]
@emman27 We can switch to using viewsets and the router.
