### ISSUE TITLE
Add sample api results when no authentication is used

### ISSUE THREAD

**Issue by MichaelWashburnJr** [BrewCenter/BrewCenterAPI#30]
It would be nice to return the first 3 results of all the brew_data endpoints if no authentication is used, just for testing and seeing the data structure.

**Comment by TheArtOfPour** [comment]
Hey, I'd like to contribute and this looks like a good starting point. Mind if I work on this one?

**Comment by MichaelWashburnJr** [comment]
It's all yours! I haven't thought about how this might be implemented yet, but let me know if you have questions.

**Comment by TheArtOfPour** [comment]
PR'd :octocat:
