### ISSUE TITLE
Add view to suggest new fermentable types

### ISSUE THREAD

**Issue by MichaelWashburnJr** [BrewCenter/BrewCenterAPI#39]
Description: #32
Depends on: #23

**Comment by moodys28** [comment]
moodys28

I would like to work on this.

**Comment by MichaelWashburnJr** [comment]
@moodys28 This heavily depends on #47, I should have put a blocked tag on this and all the data suggestion issues right now. I would suggest #43 if you'd like to get involved. It's fairly well described now and not blocked by anything. Also, we have a slack if you're not in it already! in case you want to discuss
