### ISSUE TITLE
Add master index view where users can fetch all the brew data in the api with one request.

### ISSUE THREAD

**Issue by MichaelWashburnJr** [BrewCenter/BrewCenterAPI#41]
I would like the api to have a single view that returns all the data in the api. Things should be separated logically by type, of course. The purpose of this endpoint is for applications calling this API to update their internal data.

BONUS POINTS: Implement a method of using query parameters such that you can request to be sent all the data in the api that was created after X date.

**Comment by TheArtOfPour** [comment]
May I? I like the idea for bonus points but it might warrant it's own issue. Maybe we could implement a lastupdate or rowversion param for the existing endpoints. Then, so long as the request is passed through to the views the master index would also be date filtered. Maybe build a query filter helper function into a parent view class? Having some inheritance would let us clean up some of the duplicated view code also. Cheers!

**Comment by MichaelWashburnJr** [comment]
I believe DRF already has some support for query parameters. If you'd like to create separate, dedicated issues for what you think needs to be done then feel free, I'll also try and do some investigation in the meantime

**Comment by TheArtOfPour** [comment]
PR up :) I'll start looking into the date filter.
