### ISSUE TITLE
Error when executing `python manage.py updatedata`

### ISSUE THREAD

**Issue by milrob** [BrewCenter/BrewCenterAPI#73]
Following the README, I get the following error when running the updatedata command:

`    query = 'INSERT INTO fermentable({0}) VALUES({1});'.format(Fermentable.get_keys(), str(f))
TypeError: unbound method get_keys() must be called with Fermentable instance as first argument (got nothing instead)`

**Comment by MichaelWashburnJr** [comment]
That's very strange. Was this on master, with the `python manage.py updatedata` commend? I can't seem to reproduce it on my end

**Comment by milrob** [comment]
Oh, I was using Python 2, switched to 3.6 and it works fine.
